theme:
    name: material
    palette:
        scheme: slate
extra_css:
    - css/labs.css
markdown_extensions:
    - admonition
nav:
    - index.md
    - 01_getting_started.md
    - 02_planning.md
    - 03_developing.md
    - 04_execution.md
    - 05_analytics.md
    - 06_presentation.md
    - 99_resources.md