theme: material
repo_url: https://github.com/blockscience-labs/labs-documentation
site_url: https://app.blocksciencelabs.com/project/115/documentation
nav:
    - index.md
    - index2.md
markdown_extensions:
    - toc:
        permalink: true